vote-link: "https://minecraft-server.eu/server/index/2228C/WaterDropMC"
vote-message: "Klicke auf folgenden Link, um für den Server zu voten:"
permission-message: "DU HAST KEINE RECHTE. DU BRAUCHST DIE PERMISSION: vote.use!"
no-player-message: "DU BIST KEIN SPIELER"